spring: 
    profiles: 
        active: dev
---
server: 
    port: 8080
spring: 
    application: 
        name: application-3
    profiles: dev
        
---
server: 
    port: 9090
spring: 
    application: 
        name: application-10
    profiles: test