spring: 
    profiles: 
        active: dev
---
eureka: 
    client: 
        fetchRegistry: false
        registerWithEureka: false
server: 
    port: 8763
spring: 
    application: 
        name: eureka-server-dev-2
    profiles: dev
        
---
eureka: 
    client: 
        fetchRegistry: false
        registerWithEureka: false
server: 
    port: 8762
spring: 
    application: 
        name: eureka-server-test
    profiles: test